# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ChaosOS
description: A custom image for ultimate Chaos

base-image: ghcr.io/ublue-os/base-main
image-version: 41

modules:
  - type: dnf
    install:
      packages:
        - xorg-x11-server-Xwayland
        - plymouth
        - plymouth-theme-spinner
        - systemd-udev
        #- sddm
        - network-manager-applet
        - micro
        - starship
        - lightdm
        - lightdm-gtk-greeter
        - pcmanfm
        - lxpanel
        - lxsession
        - openbox
        - lxde-common
        - lxappearance
        - lxterminal
        - lxtask
        - lxrandr
        - lxpolkit
        - lxinput
        - leafpad
        - gpicview
        - xarchiver
        - lxdm
        - lxsession-edit
        - lxshortcut
         # XFCE Core packages
        # xfce4-panel
        # xfce4-settings
        # xfce4-session
        # xfwm4
        # thunar
        # tumbler
        # ristretto
        # xfce4-terminal
        # mousepad
        # xarchiver
    remove:
      packages:
        - firefox
        - firefox-langpacks
        # Ensure only one desktop environment is layered at once
        #- lxde-desktop
        #- xfce-desktop-environment

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          #- io.gitlab.librewolf-community
          - io.github.ungoogled_software.ungoogled_chromium
          - org.libreoffice.LibreOffice
          #- com.github.marhkb.Pods
          - org.gnome.Loupe
          - com.vscodium.codium-insiders
      - scope: user
