# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ChaosOS
description: A custom image for ultimate chaos (so much so that i am not going to even bother signing it), running a mutable desktop on a Fedora Rawhide base.

base-image: ghcr.io/ublue-os/base-main
image-version: rawhide

modules:
  - type: dnf
    install:
      packages:
        - xorg-x11-server-Xwayland
        - plymouth
        - plymouth-theme-spinner
        - systemd-udev
        - sddm
        - network-manager-applet
        - micro
        - starship
        - lightdm
        - lightdm-gtk-greeter
      group-packages:
        # Pick one desktop to install at a time for maximum chaos.
        #- xfce-desktop-environment
         - lxde-desktop
    remove:
      packages:
        - firefox
        - firefox-langpacks
        # Ensure only one desktop environment is layered at once
        #- lxde-desktop
        #- xfce-desktop-environment

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user
